### ISSUE TITLE
When will you plan to release the pretrained model?

### ISSUE THREAD

**Issue by raywzy** [csxmli2016/ASFFNet#1]

**Comment by csxmli2016** [comment]
After the sponsor's approval, we will release the code and pretrained model.

**Comment by csxmli2016** [comment]
> _No description provided._

Hi, we still are not allowed to release the code, but we finally decide to release it, which is totally re-implemented on new dataset and new degradation model. Please refer to https://github.com/csxmli2016/ASFFNet512
