### ISSUE TITLE
so could you please open source this project？

### ISSUE THREAD

**Issue by Kawamiya** [csxmli2016/ASFFNet#2]

**Comment by Kawamiya** [comment]
I have learned GWANet and also want to use the similar method on face restoration, your essay and project impressed me a lot. So I want to refer to your work. Could you open source or do you have the plan to show your method?

**Comment by csxmli2016** [comment]
> I have learned GWANet and also want to use the similar method on face restoration, your essay and project impressed me a lot. So I want to refer to your work. Could you open source or do you have the plan to show your method?

Hi, thanks for your interest. However, this work is still in the contract period, and I cannot release it without the approval of our sponsor.

**Comment by csxmli2016** [comment]
> _No description provided._

But you can refer to our new work DFDNet (https://github.com/csxmli2016/DFDNet), which has a better performance than this one.

**Comment by tachikoma777** [comment]
> > _No description provided._
> 
> But you can refer to our new work DFDNet (https://github.com/csxmli2016/DFDNet), which has a better performance than this one.

Hi, great work! But one questions though, why is blind restoration better than ASFFNet with high-quality reference image of the same identity? Is there any work which got better performance with reference?

**Comment by LorenzoAgnolucci** [comment]
@tachikoma777 Hello! Have you found another work that has better performance with reference (even by other authors)? Thanks in advance

**Comment by tachikoma777** [comment]
@LorenzoAgnolucci   Hi, sadly no, seem pure blind is more poplular. Many SOTA method get strong artifact in real-world test set, I hope reference img could help this, but no clue yet, have you found anything?

**Comment by LorenzoAgnolucci** [comment]
Unfortunately not. Thanks for your answer.

**Comment by csxmli2016** [comment]
> I have learned GWANet and also want to use the similar method on face restoration, your essay and project impressed me a lot. So I want to refer to your work. Could you open source or do you have the plan to show your method?

Hi, we finally decide to release it, which is totally re-implemented on new dataset and new degradation model. Please refer to https://github.com/csxmli2016/ASFFNet512
