### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [csxmli2016/ASFFNet#4]
Hello, this project could be very useful for me. Any chance that you will release the code soon?

Thanks in advance.

**Comment by csxmli2016** [comment]
> Hello, this project could be very useful for me. Any chance that you will release the code soon?
> 
> Thanks in advance.

Hi, we still are not allowed to release the code, but we finally decide to release it, which is totally re-implemented on new dataset and new degradation model. Please refer to https://github.com/csxmli2016/ASFFNet512
