### ISSUE TITLE
Hi! 

### ISSUE THREAD

**Issue by scj0709** [csxmli2016/ASFFNet#5]
Hi! Li.
I am really impressed with your paper.
Could you tell me in detail what image was used as the training set or how it was selected?
Thank you so much for reading.
I would be very happy if you reply.

**Comment by tachikoma777** [comment]
@csxmli2016    Since you promised to release the code in the paper, please at least provide how the dataset is selected. Thanks

**Comment by 2blackbar** [comment]
They got paid to not release it, they wont do it

**Comment by csxmli2016** [comment]
> Hi! Li. I am really impressed with your paper. Could you tell me in detail what image was used as the training set or how it was selected? Thank you so much for reading. I would be very happy if you reply.

Hi, we still are not allowed to release the code, but we finally decide to release it, which is totally re-implemented on new dataset and new degradation model. Please refer to https://github.com/csxmli2016/ASFFNet512
